### ISSUE TITLE
Singularity.deepbinner-api

### ISSUE THREAD

**Issue by MPourjam** [vibaotram/baseDmux#4]
Dear Vi Bao Team;

I am trying to install you package and unfortunately keep being thrown the error that "The 'conda' command is not available inside your singularity container image. Snakemake mounts your conda installation into singularity. Sometimes, this can fail because of shell restrictions. It has been tested to work with docker://ubuntu, but it e.g. fails with docker://bash".
I am using Ubuntu 20.04.
I was wondering if you could help me on this issue or take into account some probable issues in the code.

Best Wishes,
Mohsen

**Comment by vibaotram** [comment]
Dear Mohsen,

Thank you for using the package and reporting the issue!
Sometimes I get the same error message when the singularity image is not completely installed.
If it is your case, the solution is to find the folder `.snakemake/singularity/` inside baseDmux working folder and delete it, or reinstall the package.
If this solution does not help, please send me the config files that you use to run.

Best regards
Tram

**Comment by scunnac** [comment]
In the absence of feedback, consider the issue settled.
